[package]
name = "tracker-desktop"
version = "0.1.0"
edition = "2021"
build = "build.rs"

[dependencies]
tauri = { version = "2.9.0", features = [] }
serde = { version = "1", features = ["derive"] }
serde_json = "1"
reqwest = { version = "0.11", default-features = false, features = ["json", "gzip", "rustls-tls", "blocking"] }
dirs = "5"
regex = "1.11"
urlencoding = "2.1"

[build-dependencies]
tauri-build = { version = "2.5.0", features = [] }

